"use client";
import "./globals.css";
import { Inter } from "next/font/google";
import { ShowToastContext } from "@/context/ShowToastContext";
import { ParentFolderIdContext } from "@/context/ParentFolderContext";
import { AuthProvider } from "./Provider";
import { useState } from "react";
import Header from "@/components/Header";
import Toast from "@/components/Toast";
import Footer from "@/components/Footer";

const inter = Inter({ subsets: ["latin"] });

// export const metadata = {
//   title: "Create Next App",
//   description: "Generated by create next app",
// };

export default function RootLayout({ children }) {
  const [showToastMsg, setShowToastMsg] = useState();
  const [parentFolderId, setParentFolderId] = useState();

  return (
    <html lang="en">
      <body className={inter.className}>
        <ParentFolderIdContext.Provider
          value={{ parentFolderId, setParentFolderId }}
        >
          <ShowToastContext.Provider value={{ showToastMsg, setShowToastMsg }}>
            <AuthProvider>
              <Header />
              <div>{children}</div>
              <Footer />
              {showToastMsg ? <Toast msg={showToastMsg} /> : null}
            </AuthProvider>
          </ShowToastContext.Provider>
        </ParentFolderIdContext.Provider>
      </body>
    </html>
  );
}
